name = rcp_page
description = The main layout for the Reese Creative Panels theme.
preview = preview.png
template = rcp_page-layout

; Regions
regions[branding]       = Branding
regions[content]        = Content
regions[nav01]   	    = Nav level 1
regions[nav02]   	    = Nav level 2
regions[nav03]   	    = Nav level 3
regions[background]		= Background Image
regions[content]		= content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/rcp_page/rcp_page.layout.css
